use_frameworks!

#platform :ios, '9.0'

target 'GlobalModule_Example' do
  pod 'GlobalModule', :path => '../'
#  pod 'CRRefresh'#, '1.1.3'
#  pod 'Kingfisher'
#  pod 'JGProgressHUD'
#  pod 'TransitionButton', '0.5.2'
#  pod 'IQKeyboardManagerSwift', '6.5.6'
#  pod 'DRPLoadingSpinner'

  target 'GlobalModule_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
#      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
