use_frameworks!

#platform :ios, '9.0'

target 'GlobalModule_Example' do
  pod 'GlobalModule', :path => '../'
#  pod 'Alamofire', '4.9.0'
#  pod 'RxSwift'#, '~> 5'
#  pod 'RxCocoa', '~> 5'
#  pod 'RxAlamofire'

  target 'GlobalModule_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
